MAX_LENGHT_NAME = 150
MAX_LENGHT_SMALL = 10
MAX_LENGHT_TAG_SLUG = 32
MAX_LENGHT_TAG_NAME = 32
MAX_LENGHT_INGREDIENT_MEASUREMENT_UNIT = 64
MAX_LENGHT_INGREDIENT_NAME = 128
DEFAULT_PAGE_SIZE = 6
COOKING_TIME_MIN = AMOUNT_RECIPE_INGREDIENT_MIN = 1
COOKING_TIME_MAX = AMOUNT_RECIPE_INGREDIENT_MAX = 32000
