volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:

    image: postgres:14.8-bullseye
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:

    image: jacka42/foodgram_backend
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:

    image: jacka42/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  gateway:

    image: jacka42/foodgram_gateway
    restart: always
    ports:
      - 8000:80
    volumes:
      - static_volume:/static/
      - media_volume:/var/html/media/
    depends_on:
      - frontend
